### PR TITLE
Align search

### PR DESCRIPTION
**Pull request by CamLatimer**
Hey! 

This has the search results and search bar aligned.  I just updated the tachyons padding classes.  That way, the widths and padding of the elements got things sitting nicely together.  

update: I noticed this brings a lot of previous commits with it that I didn't do. I guess I went wrong working somewhere while working on my fork locally.  Please let me know if I should re-do anything.

### CODE REVIEW

**Comment by jarrighi** [comment]
Hi Cam, thanks for this! Sorry this been waiting a while. I'll take a look tonight.

**Comment by CamLatimer** [comment]
@jarrighi Hey. No worries. I'll look out for feedback. Thanks!

**Comment by jarrighi** [comment]
Hi @CamLatimer , it was a bit confusing for me to write a case for something that wasn't merged to master yet! The tachyons code is merged now. Would you mind updating master on your fork and branching from there? Then it can be merged into master here. Let me know if you need help with that!

**Comment by CamLatimer** [comment]
Hey, @jarrighi.  Thanks again for looking at the changes. I pulled down the most recent changes from your master branch and added them to the branches on my fork.  Hoping that sets things up correctly for the merge.  If not, let me know what steps to take, and I'll follow through.

**Comment by jarrighi** [comment]
Hey @CamLatimer Can you try changing the base branch to master? I think that will probably fix the issue with the extra commits. You can do that by editing your pull request and selecting master from the `base:` branch dropdown.
screen shot 2018-06-16 at 4 32 00 pm

**Pull request closed without merging**
